version: '2'

services:
  silk:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../project:/usr/src/silk/project
      - ../silk:/usr/src/silk/silk
    environment:
      DB_ENGINE: sqlite3
      DB_NAME: db.sqlite3
