# Generated by Django 2.1.7 on 2019-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0006_fix_request_prof_file_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='path',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='view_name',
            field=models.TextField(blank=True, db_index=True, default='', null=True),
        ),
    ]
