# Generated by Django 2.1.11 on 2019-08-16 14:07

from django.db import migrations, models
import silk.storage


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0006_fix_request_prof_file_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='body',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='prof_file',
            field=models.FileField(blank=True, max_length=300, null=True, storage=silk.storage.ProfilerResultStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='pyprofile',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='query_params',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='raw_body',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
