# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import silk.storage


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0007_sqlquery_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='revision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
