# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-01-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import silk.storage


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0007_add_support_oracle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='prof_file',
            field=models.FileField(default='', max_length=300, null=True, storage=silk.storage.ProfilerResultStorage(), upload_to=b''),
        ),
    ]
