# Generated by Django 2.2.24 on 2021-06-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silk", "0008_sqlquery_analysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SQLQueryDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("traceback", models.TextField()),
                ("analysis", models.TextField()),
                (
                    "query_obj",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="silk.SQLQuery",
                    ),
                ),
            ],
        ),
    ]
