# Generated by Django 5.2.17 on 2026-08-21 12:49

from django.db import migrations, models

import silk.models


class Migration(migrations.Migration):

    dependencies = [
        ("silk", "0008_sqlquery_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="prof_file",
            field=models.FileField(
                blank=True,
                max_length=300,
                storage=silk.models.get_silk_storage,
                upload_to="",
            ),
        ),
    ]
