# Generated by Django 2.2.24 on 2021-06-24 09:54

from django.db import migrations, reset_queries

BATCH_SIZE = 100


def fill_query_details(apps, schema_editor):
    SQLQueryDetails = apps.get_model("silk", "SQLQueryDetails")
    SQLQuery = apps.get_model("silk", "SQLQuery")
    queries = SQLQuery.objects.all().order_by("pk")
    buffer = []
    for query in queries.iterator(BATCH_SIZE):
        buffer.append(
            SQLQueryDetails(
                query_obj=query,
                query=query.query,
                traceback=query.traceback,
                analysis=query.analysis or "",
            )
        )
        if len(buffer) == BATCH_SIZE:
            SQLQueryDetails.objects.bulk_create(buffer, BATCH_SIZE)
            reset_queries()  # query log leads to massive memory issue
            buffer = []


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("silk", "0009_sqlquerydetails"),
    ]

    operations = [migrations.RunPython(fill_query_details, backwards)]
