# Generated by Django 2.2.24 on 2021-06-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("silk", "0010_fill_query_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlquery",
            name="analysis",
        ),
        migrations.RemoveField(
            model_name="sqlquery",
            name="query",
        ),
        migrations.RemoveField(
            model_name="sqlquery",
            name="traceback",
        ),
    ]
