from silk.tests.unit.test_code_gen_curl import *
from silk.tests.unit.test_collector import *
from silk.tests.unit.test_dynamic_profiling import *
from silk.tests.unit.test_execute_sql import *
from silk.tests.unit.test_silky_middleware import *
from silk.tests.unit.test_silky_profiler import *
from silk.tests.unit.test_view_profiling import *
from silk.tests.unit.test_view_requests import *
from silk.tests.unit.test_end_points import *
from silk.tests.unit.test_config_auth import *
from silk.tests.unit.test_config_max_body_size import *
from silk.tests.unit.test_config_meta import *
from silk.tests.unit.test_view_sql_detail import *
from silk.tests.unit.test_filters import *
from silk.tests.unit.test_encoding import *
from silk.tests.int.test_es import *